import { Poppins } from "next/font/google";
import "./style/main.css";
import "./style/card.css";

const poppins = Poppins({
  subsets: ["latin"], // Add additional subsets as needed
  weight: ["400", "500", "700"], // Specify desired font weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
